# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1463, 913)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_file_name = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_file_name.sizePolicy().hasHeightForWidth())
        self.label_file_name.setSizePolicy(sizePolicy)
        self.label_file_name.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_file_name.setFont(font)
        self.label_file_name.setObjectName("label_file_name")
        self.horizontalLayout_10.addWidget(self.label_file_name)
        self.label_saved = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_saved.sizePolicy().hasHeightForWidth())
        self.label_saved.setSizePolicy(sizePolicy)
        self.label_saved.setMinimumSize(QtCore.QSize(200, 0))
        self.label_saved.setText("")
        self.label_saved.setObjectName("label_saved")
        self.horizontalLayout_10.addWidget(self.label_saved)
        self.label_comment = QtWidgets.QLabel(self.frame)
        self.label_comment.setWordWrap(True)
        self.label_comment.setObjectName("label_comment")
        self.horizontalLayout_10.addWidget(self.label_comment)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_8.addWidget(self.listWidget)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 576, 785))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.input_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_table.sizePolicy().hasHeightForWidth())
        self.input_table.setSizePolicy(sizePolicy)
        self.input_table.setAlternatingRowColors(True)
        self.input_table.setRowCount(100)
        self.input_table.setObjectName("input_table")
        self.input_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.input_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.read_file = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.read_file.setObjectName("read_file")
        self.horizontalLayout.addWidget(self.read_file)
        self.clear = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.plot_input = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.plot_input.setObjectName("plot_input")
        self.horizontalLayout.addWidget(self.plot_input)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.p_is_min = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.p_is_min.setChecked(True)
        self.p_is_min.setObjectName("p_is_min")
        self.horizontalLayout_9.addWidget(self.p_is_min)
        self.p_min = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.p_min.setDecimals(4)
        self.p_min.setMaximum(999.0)
        self.p_min.setObjectName("p_min")
        self.horizontalLayout_9.addWidget(self.p_min)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.p_fix = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.p_fix.setChecked(True)
        self.p_fix.setObjectName("p_fix")
        self.gridLayout.addWidget(self.p_fix, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.protein = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.protein.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.protein.setDecimals(4)
        self.protein.setMaximum(999.0)
        self.protein.setSingleStep(0.1)
        self.protein.setProperty("value", 0.2)
        self.protein.setObjectName("protein")
        self.gridLayout.addWidget(self.protein, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.Nfactor = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.Nfactor.setDecimals(4)
        self.Nfactor.setMaximum(999.0)
        self.Nfactor.setSingleStep(0.1)
        self.Nfactor.setProperty("value", 0.14)
        self.Nfactor.setObjectName("Nfactor")
        self.gridLayout.addWidget(self.Nfactor, 3, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.p_is_max = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.p_is_max.setObjectName("p_is_max")
        self.horizontalLayout_11.addWidget(self.p_is_max)
        self.p_max = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.p_max.setDecimals(4)
        self.p_max.setMaximum(999.0)
        self.p_max.setObjectName("p_max")
        self.horizontalLayout_11.addWidget(self.p_max)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.kd_is_max = QtWidgets.QCheckBox(self.groupBox)
        self.kd_is_max.setObjectName("kd_is_max")
        self.horizontalLayout_3.addWidget(self.kd_is_max)
        self.kd_max = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.kd_max.setDecimals(4)
        self.kd_max.setMaximum(999.0)
        self.kd_max.setObjectName("kd_max")
        self.horizontalLayout_3.addWidget(self.kd_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.kd_is_min = QtWidgets.QCheckBox(self.groupBox)
        self.kd_is_min.setObjectName("kd_is_min")
        self.horizontalLayout_2.addWidget(self.kd_is_min)
        self.kd_min = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.kd_min.setDecimals(4)
        self.kd_min.setMaximum(999.0)
        self.kd_min.setObjectName("kd_min")
        self.horizontalLayout_2.addWidget(self.kd_min)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.kd = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.kd.setDecimals(4)
        self.kd.setMaximum(999.0)
        self.kd.setSingleStep(0.1)
        self.kd.setProperty("value", 1.0)
        self.kd.setObjectName("kd")
        self.gridLayout_2.addWidget(self.kd, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 3)
        self.dm = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dm.setDecimals(4)
        self.dm.setMaximum(999.0)
        self.dm.setObjectName("dm")
        self.gridLayout_2.addWidget(self.dm, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 3)
        self.kd_fix = QtWidgets.QCheckBox(self.groupBox)
        self.kd_fix.setObjectName("kd_fix")
        self.gridLayout_2.addWidget(self.kd_fix, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dm_is_max = QtWidgets.QCheckBox(self.groupBox)
        self.dm_is_max.setObjectName("dm_is_max")
        self.horizontalLayout_5.addWidget(self.dm_is_max)
        self.dm_max = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dm_max.setDecimals(4)
        self.dm_max.setMaximum(999.0)
        self.dm_max.setObjectName("dm_max")
        self.horizontalLayout_5.addWidget(self.dm_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 7, 2, 1, 1)
        self.dm_fix = QtWidgets.QCheckBox(self.groupBox)
        self.dm_fix.setObjectName("dm_fix")
        self.gridLayout_2.addWidget(self.dm_fix, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dm_is_min = QtWidgets.QCheckBox(self.groupBox)
        self.dm_is_min.setObjectName("dm_is_min")
        self.horizontalLayout_4.addWidget(self.dm_is_min)
        self.dm_min = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dm_min.setDecimals(4)
        self.dm_min.setMaximum(999.0)
        self.dm_min.setObjectName("dm_min")
        self.horizontalLayout_4.addWidget(self.dm_min)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        self.start = QtWidgets.QPushButton(self.groupBox)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 8, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setEnabled(True)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 575, 785))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidget_2Page1 = QtWidgets.QWidget()
        self.tabWidget_2Page1.setObjectName("tabWidget_2Page1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabWidget_2Page1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.plot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setMinimumSize(QtCore.QSize(0, 0))
        self.plot.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.plot.setText("")
        self.plot.setAlignment(QtCore.Qt.AlignCenter)
        self.plot.setObjectName("plot")
        self.verticalLayout_4.addWidget(self.plot)
        self.tabWidget_2.addTab(self.tabWidget_2Page1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_9.addWidget(self.textEdit_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.setDef = QtWidgets.QPushButton(self.tab_3)
        self.setDef.setObjectName("setDef")
        self.horizontalLayout_7.addWidget(self.setDef)
        self.restoreDef = QtWidgets.QPushButton(self.tab_3)
        self.restoreDef.setObjectName("restoreDef")
        self.horizontalLayout_7.addWidget(self.restoreDef)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_8.addWidget(self.scrollArea_2)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.horizontalLayout_6.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1463, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPoint = QtWidgets.QMenu(self.menubar)
        self.menuPoint.setObjectName("menuPoint")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionOpen_project = QtWidgets.QAction(MainWindow)
        self.actionOpen_project.setObjectName("actionOpen_project")
        self.actionNew_set = QtWidgets.QAction(MainWindow)
        self.actionNew_set.setObjectName("actionNew_set")
        self.actionRead_set = QtWidgets.QAction(MainWindow)
        self.actionRead_set.setObjectName("actionRead_set")
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew_File.setIcon(icon)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen_file.setIcon(icon)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionNew_set_2 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.actionNew_set_2.setIcon(icon)
        self.actionNew_set_2.setObjectName("actionNew_set_2")
        self.actionEdit_file_info = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionEdit_file_info.setIcon(icon)
        self.actionEdit_file_info.setObjectName("actionEdit_file_info")
        self.actionEdit_set = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionEdit_set.setIcon(icon)
        self.actionEdit_set.setObjectName("actionEdit_set")
        self.actionDelete_point = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.actionDelete_point.setIcon(icon)
        self.actionDelete_point.setObjectName("actionDelete_point")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopy_to_clipboard = QtWidgets.QAction(MainWindow)
        self.actionCopy_to_clipboard.setObjectName("actionCopy_to_clipboard")
        self.actionSave_as_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_as_2.setObjectName("actionSave_as_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocs = QtWidgets.QAction(MainWindow)
        self.actionDocs.setObjectName("actionDocs")
        self.actionCalculate_average_value = QtWidgets.QAction(MainWindow)
        self.actionCalculate_average_value.setObjectName("actionCalculate_average_value")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionEdit_file_info)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionCalculate_average_value)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuPoint.addAction(self.actionNew_set_2)
        self.menuPoint.addAction(self.actionEdit_set)
        self.menuPoint.addAction(self.actionDelete_point)
        self.menuPlot.addAction(self.actionCopy_to_clipboard)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPoint.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Binding Constant Calculator"))
        self.label_file_name.setText(_translate("MainWindow", "File:"))
        self.label_comment.setText(_translate("MainWindow", "Comment:"))
        self.label.setText(_translate("MainWindow", "Input data:"))
        item = self.input_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ligand ratio"))
        item = self.input_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "H"))
        item = self.input_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "N"))
        self.read_file.setText(_translate("MainWindow", "Read from file"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.plot_input.setText(_translate("MainWindow", "Plot"))
        self.p_is_min.setText(_translate("MainWindow", "min:"))
        self.p_fix.setText(_translate("MainWindow", "Fixed"))
        self.label_2.setText(_translate("MainWindow", "Protein concentration:"))
        self.label_3.setText(_translate("MainWindow", "mM"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Nitrogen scaling factor (α):</p></body></html>"))
        self.p_is_max.setText(_translate("MainWindow", "max:"))
        self.groupBox.setTitle(_translate("MainWindow", "Fitting parameters:"))
        self.kd_is_max.setText(_translate("MainWindow", "max:"))
        self.kd_is_min.setText(_translate("MainWindow", "min:"))
        self.label_6.setText(_translate("MainWindow", "Initial value:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Binding constant (K<sub>d</sub>):</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Initial value:"))
        self.label_7.setText(_translate("MainWindow", "mM"))
        self.label_10.setText(_translate("MainWindow", "ppm"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Normalized chemical shift change limit δ<span style=\" vertical-align:sub;\">max</span>:</p></body></html>"))
        self.kd_fix.setText(_translate("MainWindow", "Fixed"))
        self.dm_is_max.setText(_translate("MainWindow", "max:"))
        self.dm_fix.setText(_translate("MainWindow", "Fixed"))
        self.dm_is_min.setText(_translate("MainWindow", "min:"))
        self.start.setText(_translate("MainWindow", "Start fitting"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page1), _translate("MainWindow", "Plot"))
        self.setDef.setText(_translate("MainWindow", "Set as default"))
        self.restoreDef.setText(_translate("MainWindow", "Restore default"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Plot settings"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fitting results"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuPoint.setTitle(_translate("MainWindow", "Po&int"))
        self.menuPlot.setTitle(_translate("MainWindow", "P&lot"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_project.setText(_translate("MainWindow", "&New project"))
        self.actionOpen_project.setText(_translate("MainWindow", "&Open project"))
        self.actionNew_set.setText(_translate("MainWindow", "New &set"))
        self.actionRead_set.setText(_translate("MainWindow", "&Read set"))
        self.actionNew_File.setText(_translate("MainWindow", "&New File"))
        self.actionNew_File.setIconText(_translate("MainWindow", "New file"))
        self.actionNew_File.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen_file.setText(_translate("MainWindow", "&Open file"))
        self.actionOpen_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save &as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionNew_set_2.setText(_translate("MainWindow", "&New point"))
        self.actionNew_set_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionEdit_file_info.setText(_translate("MainWindow", "&Edit file info"))
        self.actionEdit_set.setText(_translate("MainWindow", "&Edit point name"))
        self.actionDelete_point.setText(_translate("MainWindow", "&Delete point"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionCopy_to_clipboard.setText(_translate("MainWindow", "&Copy to clipboard"))
        self.actionSave_as_2.setText(_translate("MainWindow", "&Save as"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionDocs.setText(_translate("MainWindow", "&User manual"))
        self.actionCalculate_average_value.setText(_translate("MainWindow", "&Calculate average value"))

